Description:  This template deploys a lambda function in Development and Production Environments
Parameters:
  EnvironmentType:
    Description: Environment Name
    Type: String
    Default: DEVELOPMENT
    AllowedValues: [DEVELOPMENT,PRODUCTION]

Mappings:
  Environments:
    DEVELOPMENT:
      LAMBDANAME: jaz-lambda-development                #Change this to your lambda name
    PRODUCTION:
      LAMBDANAME: jaz-lambda-production                 #Change this to your lambda name

Resources:
  MyLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            print("Hello, World!")
            return "Hello, World!"
      Handler: index.lambda_handler
      FunctionName: !FindInMap [Environments, !Ref EnvironmentType, LAMBDANAME]
      Role: !GetAtt MyLambdaRole.Arn
      Runtime: python3.7
      Timeout: 3

  MyLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"