AWSTemplateFormatVersion: "2010-09-09"
Resources:
  myTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: jaz-dynamodbtable   #Replace this with your table name
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: ID
        AttributeType: S
      KeySchema:
      - AttributeName: ID
        KeyType: HASH