Resources:
  MyLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            print("Hello, World!")
            return "Hello, World!"
      Handler: index.lambda_handler
      FunctionName: jaz-cloudformation-lambda     ##Replace this with your function name e.g. <your-name>-cloudformation-lambda
      Role: !GetAtt MyLambdaRole.Arn
      Runtime: python3.7
      Timeout: 3

  MyLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"